# Generated by Django 6.0.2 on 2026-03-19 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredients',
            new_name='recipe_description',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='instructions',
            new_name='recipe_ingredients',
        ),
    ]
