# Generated by Django 6.0.2 on 2026-03-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0003_recipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_views_count',
            field=models.IntegerField(default=1),
        ),
    ]
